// <auto-generated />
using Csv.Api.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Csv.Api.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEnd.Models.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hora");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("temperatura");

                    b.HasKey("Id");

                    b.ToTable("tb_temperature");
                });
#pragma warning restore 612, 618
        }
    }
}
